### ISSUE TITLE
Error in libimobiledevice: Not Enough Data

### ISSUE THREAD

**Issue by hzx1987227** [gh2o/rvi_capture#4]
Hello there,

I got this error:

capturing to <stdout> ...
�ò�          ����
Traceback (most recent call last):
  File "C:\Users\Bird\Downloads\rvi_capture-master\rvi_capture-master\rvi_capture.py", line 364, in <module>
    main()
  File "C:\Users\Bird\Downloads\rvi_capture-master\rvi_capture-master\rvi_capture.py", line 354, in main
    packet_dumper.run(packet_callback)
  File "C:\Users\Bird\Downloads\rvi_capture-master\rvi_capture-master\rvi_capture.py", line 295, in run
    for pkt in self.pkt_iter:
  File "C:\Users\Bird\Downloads\rvi_capture-master\rvi_capture-master\rvi_capture.py", line 183, in __iter__
    [chunk_len] = UB32.unpack(read_fully(4))
  File "C:\Users\Bird\Downloads\rvi_capture-master\rvi_capture-master\rvi_capture.py", line 178, in read_fully
    b += conn.recv(n - l)
  File "C:\Users\Bird\Downloads\rvi_capture-master\rvi_capture-master\rvi_capture.py", line 122, in recv
    IDeviceError.check(self.idevice_connection_receive_timeout(
  File "C:\Users\Bird\Downloads\rvi_capture-master\rvi_capture-master\rvi_capture.py", line 59, in check
    raise cls(err)
__main__.IDeviceError: Error in libimobiledevice: Not Enough Data

Any idea for this?

Thank you

**Comment by gh2o** [comment]
What iOS version is your device?

**Comment by hzx1987227** [comment]
> What iOS version is your device?

iPhone X  13.1.3

**Comment by gh2o** [comment]
I have not tested iOS 13 yet. I will test it after I update my device.

**Comment by andrewmusselman** [comment]
Getting a similar error on Ubuntu with iOS 13.3:

```capturing to wifi ...

Traceback (most recent call last):
  File "./rvi_capture.py", line 364, in <module>
    main()
  File "./rvi_capture.py", line 354, in main
    packet_dumper.run(packet_callback)
  File "./rvi_capture.py", line 295, in run
    for pkt in self.pkt_iter:
  File "./rvi_capture.py", line 183, in __iter__
    [chunk_len] = UB32.unpack(read_fully(4))
  File "./rvi_capture.py", line 178, in read_fully
    b += conn.recv(n - l)
  File "./rvi_capture.py", line 123, in recv
    self.handle, out, num_bytes, ctypes.byref(out_bytes), ctypes.c_uint(500)))
  File "./rvi_capture.py", line 59, in check
    raise cls(err)
__main__.IDeviceError: Error in libimobiledevice: Not Enough Data```

**Comment by barrymcnicholl** [comment]
This is brilliant and I have used this successfully on Windows for older versions of iOS. Any luck with 13.x? Appreciate the effort.

**Comment by gh2o** [comment]
It appears that there has been a major change in protocol for iOS 13. It won't be supported for now.

**Comment by gh2o** [comment]
Support for iOS 13+ has been added (tested up to iOS 14.8).
